apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-nextcloud
  labels:
    app: postgres
spec:
  storageClassName: manual
  claimRef:
    name: postgres-volume-claim
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql-nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
