apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data
  namespace: linkding
spec:
  selector:
    app: linkding
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
